const API="https://evader-perceptual-check.wub47108.chatgpt.site/api/external-submit";
const app=document.querySelector("#app");
const assets="stimuli/";
let stage="landing",sessionId="",group="",plan=[],index=0,answers=[],started=0,trialStarted=0,selected=null,rating=null;
const methods={A:["Evader","PGD","StealthDiffusion"],B:["PGD","StealthDiffusion","Evader"],C:["StealthDiffusion","Evader","PGD"]};
const items=["dragon_01","dragon_03","dragon_05"];
const slug={Evader:"evader",PGD:"pgd",StealthDiffusion:"stealth"};

function rngFrom(text){let seed=2166136261;for(const ch of text)seed=Math.imul(seed^ch.charCodeAt(0),16777619);return()=>{seed+=0x6D2B79F5;let t=seed;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296}}
function shuffle(a,r){for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function auth(itemId,method,image){return{itemId,trialType:"authenticity",analysisSet:method==="Real"?"auth_real_control":"auth_dragon",method,reference:assets+image,candidateA:assets+image,candidateB:assets+image,correctSide:method==="Real"?"A":"B"}}
function mod(itemId,method,clean,modified,side,analysisSet){return{itemId,trialType:"modification",analysisSet,method,reference:assets+clean,candidateA:assets+(side==="A"?modified:clean),candidateB:assets+(side==="B"?modified:clean),correctSide:side}}
function buildPlan(id,g){const r=rngFrom(id),condition=g.endsWith("0")?"Clean":"Evader",ending=condition==="Clean"?"clean":"evader";const a=[auth("real_01","Real","real_01.png"),auth("real_02","Real","real_02.png"),...items.map(x=>auth("auth_"+x,condition,`${x}_${ending}.png`))];shuffle(a,r);const p=items.map((x,i)=>{const m=methods[g[0]][i];return mod(x,m,`${x}_clean.png`,`${x}_${slug[m]}.png`,r()<.5?"A":"B","primary_dragon")});shuffle(p,r);const attention=mod("attention_01","Attention","attention_clean.png","attention_modified.png",r()<.5?"A":"B","attention_check");const fig10=mod("fig10_01","Fig10-Evader","fig10_clean.png","fig10_evader.png",r()<.5?"A":"B","reviewer_fig10");return[...a,p[0],p[1],attention,p[2],fig10]}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}

function render(){if(stage==="landing")return landing();if(stage==="instructions")return instructions();if(stage==="trial")return trial();if(stage==="submitting")return message("正在保存匿名回答…","请不要关闭页面。");}
function landing(){app.className="panel landing";app.innerHTML=`<p class="eyebrow">Anonymous visual study</p><h1>图像来源与细微变化测试</h1><p class="lead">测试分为两个很短的部分：先判断图片是真实拍摄还是 AI 生成，再判断哪张候选图发生了变化。</p><div class="facts"><div class="fact"><b>约 3 分钟</b><small>全程仅 10 道</small></div><div class="fact"><b>匿名参加</b><small>不收集身份和 IP</small></div><div class="fact"><b>手机 / 电脑</b><small>均可直接完成</small></div></div><div class="consent"><label><input class="ok" type="checkbox">我自愿参加，并同意匿名回答用于学术研究。</label><label><input class="ok" type="checkbox">我已年满 18 周岁。</label><label><input class="ok" type="checkbox">我的视力正常或经矫正后正常。</label><label><input class="ok" type="checkbox">我以前没有参加过本测试，也没有提前看过答案。</label></div><p class="privacy">不收集姓名、微信号、邮箱、电话号码、IP 地址或浏览器标识。您可在提交前随时退出。</p><button id="start" class="primary" disabled>同意并开始</button>`;const boxes=[...document.querySelectorAll(".ok")],button=document.querySelector("#start");boxes.forEach(x=>x.onchange=()=>button.disabled=!boxes.every(y=>y.checked));button.onclick=start}
function start(){sessionId=crypto.randomUUID();group=["A0","A1","B0","B1","C0","C1"][crypto.getRandomValues(new Uint8Array(1))[0]%6];plan=buildPlan(sessionId,group);stage="instructions";render()}
function instructions(){app.className="panel landing";app.innerHTML=`<p class="eyebrow">Instructions</p><h1>作答说明</h1><p class="lead">第 1–5 题：每次显示一张图，请判断“真实拍摄”或“AI 生成”。<br>第 6–10 题：对照参考图，找出发生视觉变化的候选 A/B；部分题还需评价差异明显程度。<br><br>请凭第一直觉回答，不使用外部放大或图像工具。</p><button id="begin" class="primary">开始 10 道题</button>`;document.querySelector("#begin").onclick=()=>{stage="trial";started=performance.now();trialStarted=started;render()}}
function trial(){const t=plan[index],authenticity=t.trialType==="authenticity",needRating=["primary_dragon","reviewer_fig10"].includes(t.analysisSet);app.className="panel";app.innerHTML=`<div class="progress"><div class="track"><div class="fill" style="width:${index/plan.length*100}%"></div></div><span class="count">${index+1} / ${plan.length}</span></div><p class="section">${authenticity?"第一部分 · 图像来源":"第二部分 · 视觉变化"}</p><h2>${authenticity?"你认为这张图片来自哪里？":"哪张候选图发生了变化？"}</h2><p class="sub">${authenticity?"请凭第一直觉判断。":"先对照参考图，再选择 A 或 B。"}</p>${authenticity?`<img class="stimulus" src="${t.reference}" alt="待判断图片"><div class="choices"><button class="choice" data-side="A">📷　真实拍摄</button><button class="choice" data-side="B">✦　AI 生成</button></div>`:`<div class="reference"><span class="label">参考图</span><img class="stimulus" src="${t.reference}" alt="参考图"></div><div class="candidates">${["A","B"].map(s=>`<button class="candidate" data-side="${s}"><b>${s}</b><img class="stimulus" src="${s==="A"?t.candidateA:t.candidateB}" alt="候选图 ${s}"></button>`).join("")}</div>${needRating?`<div class="rating"><p>您所选变化图与参考图的差异有多明显？</p><div>${[1,2,3,4,5].map(n=>`<button data-rating="${n}">${n}</button>`).join("")}</div><div class="ends"><span>几乎看不出</span><span>非常明显</span></div></div>`:""}`}<div class="actions"><button id="next" class="primary" disabled>${index===plan.length-1?"提交回答":"下一题"}</button></div><p id="error" class="error"></p>`;document.querySelectorAll("[data-side]").forEach(b=>b.onclick=()=>{selected=b.dataset.side;document.querySelectorAll("[data-side]").forEach(x=>x.classList.toggle("selected",x===b));enable(needRating)});document.querySelectorAll("[data-rating]").forEach(b=>b.onclick=()=>{rating=+b.dataset.rating;document.querySelectorAll("[data-rating]").forEach(x=>x.classList.toggle("selected",x===b));enable(needRating)});document.querySelector("#next").onclick=next}
function enable(need){document.querySelector("#next").disabled=!selected||(need&&!rating)}
function next(){const t=plan[index],need=["primary_dragon","reviewer_fig10"].includes(t.analysisSet);answers.push({itemId:t.itemId,selectedSide:selected,noticeability:need?rating:0,durationMs:Math.round(performance.now()-trialStarted)});selected=null;rating=null;if(++index<plan.length){trialStarted=performance.now();scrollTo(0,0);return render()}submit()}
async function submit(){stage="submitting";render();const payload={sessionId,allocationGroup:group,totalDurationMs:Math.round(performance.now()-started),deviceType:innerWidth<=700?"mobile":"desktop",viewportWidth:innerWidth,viewportHeight:innerHeight,devicePixelRatio:devicePixelRatio||1,answers};try{const r=await fetch(API,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw Error("submit");const j=await r.json();complete(j.completionCode)}catch(e){stage="trial";index=plan.length-1;answers.pop();render();document.querySelector("#error").textContent="提交失败，请检查网络后重试。"}}
function complete(code){app.className="panel complete";app.innerHTML=`<p class="eyebrow">Completed</p><h1>感谢参加</h1><p class="lead">您的匿名回答已成功保存。请不要在群聊中讨论具体图片或答案。</p><div class="code">完成码：${esc(code)}</div><p class="privacy">现在可以关闭此页面。</p>`}
function message(title,text){app.className="panel complete";app.innerHTML=`<p class="eyebrow">Please wait</p><h1>${title}</h1><p class="lead">${text}</p>`}
render();
